#!/usr/bin/env python3
"""
Complete Signal Audit - Check all components, data, and weights
"""

from droplet_client import DropletClient
import json

def main():
    client = DropletClient()
    
    try:
        print("=" * 80)
        print("COMPLETE SIGNAL AUDIT - ALL COMPONENTS")
        print("=" * 80)
        print()
        
        result = client.execute_command(
            "cd ~/stock-bot && source venv/bin/activate && python3 << 'PYEOF'\n"
            "import sys\n"
            "sys.path.insert(0, '.')\n"
            "from main import read_uw_cache\n"
            "from uw_composite_v2 import compute_composite_score_v3, WEIGHTS_V3, get_weight\n"
            "from uw_enrichment_v2 import enrich_signal\n"
            "import json\n"
            "\n"
            "cache = read_uw_cache()\n"
            "symbol = 'AAPL'  # Best case\n"
            "data = cache.get(symbol, {})\n"
            "enriched = enrich_signal(symbol, cache, 'mixed')\n"
            "result = compute_composite_score_v3(symbol, enriched, 'mixed')\n"
            "\n"
            "print('=' * 80)\n"
            "print('SIGNAL COMPONENT AUDIT')\n"
            "print('=' * 80)\n"
            "print()\n"
            "\n"
            "# Get all components\n"
            "components = result.get('components', {})\n"
            "print(f'Total components defined: {len(components)}')\n"
            "print()\n"
            "\n"
            "# Check each component\n"
            "print('COMPONENT BREAKDOWN:')\n"
            "print('-' * 80)\n"
            "zero_components = []\n"
            "non_zero_components = []\n"
            "\n"
            "for comp_name, comp_value in sorted(components.items()):\n"
            "    weight = get_weight(comp_name)\n"
            "    status = 'ZERO' if comp_value == 0.0 else 'ACTIVE'\n"
            "    print(f'{comp_name:25} = {comp_value:8.4f}  (weight: {weight:6.3f})  [{status}]')\n"
            "    if comp_value == 0.0:\n"
            "        zero_components.append(comp_name)\n"
            "    else:\n"
            "        non_zero_components.append(comp_name)\n"
            "\n"
            "print()\n"
            "print(f'Active components: {len(non_zero_components)}/{len(components)}')\n"
            "print(f'Zero components: {len(zero_components)}/{len(components)}')\n"
            "print()\n"
            "\n"
            "# Check data availability\n"
            "print('DATA AVAILABILITY CHECK:')\n"
            "print('-' * 80)\n"
            "data_checks = {\n"
            "    'dark_pool': enriched.get('dark_pool', {}),\n"
            "    'insider': enriched.get('insider', {}),\n"
            "    'market_tide': enriched.get('market_tide', {}),\n"
            "    'calendar': enriched.get('calendar', {}),\n"
            "    'congress': enriched.get('congress', {}),\n"
            "    'institutional': enriched.get('institutional', {}),\n"
            "    'shorts': enriched.get('shorts', {}),\n"
            "    'greeks': enriched.get('greeks', {}),\n"
            "    'iv_rank': enriched.get('iv_rank', {}),\n"
            "    'oi_change': enriched.get('oi_change', {}),\n"
            "    'etf_flow': enriched.get('etf_flow', {}),\n"
            "    'ftd': enriched.get('ftd', {}),\n"
            "    'squeeze_score': enriched.get('squeeze_score', {}),\n"
            "    'iv_term_skew': enriched.get('iv_term_skew'),\n"
            "    'smile_slope': enriched.get('smile_slope'),\n"
            "    'toxicity': enriched.get('toxicity'),\n"
            "    'event_alignment': enriched.get('event_alignment'),\n"
            "    'freshness': enriched.get('freshness'),\n"
            "    'sentiment': enriched.get('sentiment'),\n"
            "    'conviction': enriched.get('conviction'),\n"
            "}\n"
            "\n"
            "for key, value in data_checks.items():\n"
            "    if value is None:\n"
            "        print(f'{key:25} = MISSING')\n"
            "    elif isinstance(value, dict):\n"
            "        has_data = len(value) > 0 and value != {}\n"
            "        print(f'{key:25} = {\"HAS DATA\" if has_data else \"EMPTY DICT\"} ({len(value)} keys)')\n"
            "        if has_data and len(value) < 5:\n"
            "            print(f'  Keys: {list(value.keys())}')\n"
            "    elif isinstance(value, (int, float)):\n"
            "        print(f'{key:25} = {value}')\n"
            "    else:\n"
            "        print(f'{key:25} = {type(value).__name__}: {str(value)[:50]}')\n"
            "\n"
            "print()\n"
            "\n"
            "# Check weights\n"
            "print('WEIGHT CONFIGURATION:')\n"
            "print('-' * 80)\n"
            "print('WEIGHTS_V3 (defaults):')\n"
            "for comp_name in sorted(components.keys()):\n"
            "    default_weight = WEIGHTS_V3.get(comp_name, 'NOT FOUND')\n"
            "    current_weight = get_weight(comp_name)\n"
            "    if default_weight != current_weight:\n"
            "        print(f'  {comp_name:25} = {default_weight:6.3f} (default) -> {current_weight:6.3f} (current) [ADAPTIVE]')\n"
            "    else:\n"
            "        print(f'  {comp_name:25} = {current_weight:6.3f} (default)')\n"
            "\n"
            "print()\n"
            "\n"
            "# Check zero components in detail\n"
            "print('ZERO COMPONENT ANALYSIS:')\n"
            "print('-' * 80)\n"
            "for comp_name in zero_components:\n"
            "    print(f'\\n{comp_name}:')\n"
            "    weight = get_weight(comp_name)\n"
            "    print(f'  Weight: {weight}')\n"
            "    \n"
            "    # Check if data exists\n"
            "    data_key_map = {\n"
            "        'whale': 'motif_whale',\n"
            "        'event': 'event_alignment',\n"
            "        'motif_bonus': 'motif_staircase',\n"
            "        'regime': 'regime',\n"
            "        'congress': 'congress',\n"
            "        'shorts_squeeze': 'shorts',\n"
            "        'institutional': 'institutional',\n"
            "        'market_tide': 'market_tide',\n"
            "        'calendar': 'calendar',\n"
            "        'greeks_gamma': 'greeks',\n"
            "        'ftd_pressure': 'ftd',\n"
            "        'iv_rank': 'iv_rank',\n"
            "        'oi_change': 'oi_change',\n"
            "        'etf_flow': 'etf_flow',\n"
            "        'squeeze_score': 'squeeze_score',\n"
            "    }\n"
            "    \n"
            "    if comp_name in data_key_map:\n"
            "        data_key = data_key_map[comp_name]\n"
            "        data_value = enriched.get(data_key, {})\n"
            "        if isinstance(data_value, dict):\n"
            "            print(f'  Data: {len(data_value)} keys')\n"
            "            if len(data_value) > 0:\n"
            "                print(f'  Keys: {list(data_value.keys())[:5]}')\n"
            "        else:\n"
            "            print(f'  Data: {data_value}')\n"
            "PYEOF",
            timeout=180
        )
        print(result['stdout'])
        print()
        
    except Exception as e:
        print(f"[ERROR] Audit failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        client.close()

if __name__ == "__main__":
    main()

