#!/usr/bin/env python3
"""
Historical Performance Analysis - Determine if poor performance was due to bugs
"""

from droplet_client import DropletClient
import json

def main():
    client = DropletClient()
    
    try:
        print("=" * 80)
        print("HISTORICAL PERFORMANCE ANALYSIS")
        print("=" * 80)
        print()
        
        result = client.execute_command(
            "cd ~/stock-bot && source venv/bin/activate && python3 << 'PYEOF'\n"
            "import sys\n"
            "sys.path.insert(0, '.')\n"
            "from pathlib import Path\n"
            "import json\n"
            "from collections import defaultdict\n"
            "\n"
            "print('ANALYZING HISTORICAL TRADE DATA')\n"
            "print('=' * 80)\n"
            "print()\n"
            "\n"
            "# 1. Load attribution data\n"
            "attribution_file = Path('logs/attribution.jsonl')\n"
            "if not attribution_file.exists():\n"
            "    attribution_file = Path('data/attribution.jsonl')\n"
            "\n"
            "trades = []\n"
            "if attribution_file.exists():\n"
            "    with attribution_file.open() as f:\n"
            "        for line in f:\n"
            "            try:\n"
            "                trade = json.loads(line.strip())\n"
            "                if trade.get('type') == 'attribution':\n"
            "                    trades.append(trade)\n"
            "            except:\n"
            "                continue\n"
            "\n"
            "print(f'Total trades found: {len(trades)}')\n"
            "print()\n"
            "\n"
            "# 2. Analyze component presence in winning vs losing trades\n"
            "winning_trades = []\n"
            "losing_trades = []\n"
            "\n"
            "for trade in trades:\n"
            "    pnl_pct = trade.get('pnl_pct', 0) or trade.get('context', {}).get('pnl_pct', 0)\n"
            "    if pnl_pct > 0:\n"
            "        winning_trades.append(trade)\n"
            "    elif pnl_pct < 0:\n"
            "        losing_trades.append(trade)\n"
            "\n"
            "print(f'Winning trades: {len(winning_trades)}')\n"
            "print(f'Losing trades: {len(losing_trades)}')\n"
            "print()\n"
            "\n"
            "# 3. Check component presence and values\n"
            "components_to_check = [\n"
            "    'dark_pool', 'greeks_gamma', 'iv_rank', 'oi_change', 'ftd_pressure',\n"
            "    'market_tide', 'regime_modifier', 'smile_slope', 'congress', 'institutional'\n"
            "]\n"
            "\n"
            "print('COMPONENT ANALYSIS - WINNING VS LOSING TRADES:')\n"
            "print('-' * 80)\n"
            "\n"
            "for comp in components_to_check:\n"
            "    wins_with_comp = 0\n"
            "    wins_with_value = 0\n"
            "    losses_with_comp = 0\n"
            "    losses_with_value = 0\n"
            "    \n"
            "    win_values = []\n"
            "    loss_values = []\n"
            "    \n"
            "    for trade in winning_trades:\n"
            "        comps = trade.get('components', {}) or trade.get('context', {}).get('components', {})\n"
            "        if comp in comps:\n"
            "            wins_with_comp += 1\n"
            "            val = comps.get(comp, 0)\n"
            "            if val != 0:\n"
            "                wins_with_value += 1\n"
            "                win_values.append(val)\n"
            "    \n"
            "    for trade in losing_trades:\n"
            "        comps = trade.get('components', {}) or trade.get('context', {}).get('components', {})\n"
            "        if comp in comps:\n"
            "            losses_with_comp += 1\n"
            "            val = comps.get(comp, 0)\n"
            "            if val != 0:\n"
            "                losses_with_value += 1\n"
            "                loss_values.append(val)\n"
            "    \n"
            "    win_pct = (wins_with_comp / len(winning_trades) * 100) if winning_trades else 0\n"
            "    loss_pct = (losses_with_comp / len(losing_trades) * 100) if losing_trades else 0\n"
            "    \n"
            "    win_value_pct = (wins_with_value / len(winning_trades) * 100) if winning_trades else 0\n"
            "    loss_value_pct = (losses_with_value / len(losing_trades) * 100) if losing_trades else 0\n"
            "    \n"
            "    avg_win_val = sum(win_values) / len(win_values) if win_values else 0\n"
            "    avg_loss_val = sum(loss_values) / len(loss_values) if loss_values else 0\n"
            "    \n"
            "    print(f'{comp:25}:')\n"
            "    print(f'  Present in wins: {wins_with_comp}/{len(winning_trades)} ({win_pct:.1f}%)')\n"
            "    print(f'  Present in losses: {losses_with_comp}/{len(losing_trades)} ({loss_pct:.1f}%)')\n"
            "    print(f'  Non-zero in wins: {wins_with_value}/{len(winning_trades)} ({win_value_pct:.1f}%)')\n"
            "    print(f'  Non-zero in losses: {losses_with_value}/{len(losing_trades)} ({loss_value_pct:.1f}%)')\n"
            "    if win_values:\n"
            "        print(f'  Avg value in wins: {avg_win_val:.4f}')\n"
            "    if loss_values:\n"
            "        print(f'  Avg value in losses: {avg_loss_val:.4f}')\n"
            "    print()\n"
            "\n"
            "# 4. Check if components were 0.0 due to bugs\n"
            "print('BUG ANALYSIS - COMPONENTS THAT SHOULD HAVE CONTRIBUTED:')\n"
            "print('-' * 80)\n"
            "\n"
            "# Check if greeks_gamma was 0.0 but greeks data existed\n"
            "greeks_zero_but_data = 0\n"
            "greeks_zero_no_data = 0\n"
            "\n"
            "for trade in trades:\n"
            "    comps = trade.get('components', {}) or trade.get('context', {}).get('components', {})\n"
            "    greeks_val = comps.get('greeks_gamma', 0)\n"
            "    \n"
            "    # Check if enriched data had greeks\n"
            "    enriched = trade.get('enriched_data', {}) or trade.get('context', {}).get('enriched_data', {})\n"
            "    greeks_data = enriched.get('greeks', {})\n"
            "    \n"
            "    if greeks_val == 0:\n"
            "        if greeks_data and len(greeks_data) > 0:\n"
            "            greeks_zero_but_data += 1\n"
            "        else:\n"
            "            greeks_zero_no_data += 1\n"
            "\n"
            "print(f'greeks_gamma was 0.0 but greeks data existed: {greeks_zero_but_data}')\n"
            "print(f'greeks_gamma was 0.0 and no greeks data: {greeks_zero_no_data}')\n"
            "print()\n"
            "\n"
            "# 5. Check score distribution\n"
            "print('SCORE DISTRIBUTION:')\n"
            "print('-' * 80)\n"
            "\n"
            "win_scores = []\n"
            "loss_scores = []\n"
            "\n"
            "for trade in winning_trades:\n"
            "    score = trade.get('entry_score', 0) or trade.get('context', {}).get('entry_score', 0) or trade.get('score', 0)\n"
            "    if score > 0:\n"
            "        win_scores.append(score)\n"
            "\n"
            "for trade in losing_trades:\n"
            "    score = trade.get('entry_score', 0) or trade.get('context', {}).get('entry_score', 0) or trade.get('score', 0)\n"
            "    if score > 0:\n"
            "        loss_scores.append(score)\n"
            "\n"
            "if win_scores:\n"
            "    print(f'Winning trade scores: min={min(win_scores):.2f}, max={max(win_scores):.2f}, avg={sum(win_scores)/len(win_scores):.2f}')\n"
            "if loss_scores:\n"
            "    print(f'Losing trade scores: min={min(loss_scores):.2f}, max={max(loss_scores):.2f}, avg={sum(loss_scores)/len(loss_scores):.2f}')\n"
            "print()\n"
            "\n"
            "# 6. Check adaptive weight state file dates\n"
            "print('ADAPTIVE WEIGHT TIMELINE:')\n"
            "print('-' * 80)\n"
            "\n"
            "state_file = Path('state/signal_weights.json')\n"
            "if state_file.exists():\n"
            "    with state_file.open() as f:\n"
            "        state = json.load(f)\n"
            "    \n"
            "    saved_at = state.get('saved_at', 0)\n"
            "    saved_dt = state.get('saved_dt', 'unknown')\n"
            "    print(f'State file last updated: {saved_dt} ({saved_at})')\n"
            "    \n"
            "    # Check when components were last updated\n"
            "    weight_bands = state.get('weight_bands', {})\n"
            "    if weight_bands:\n"
            "        print(f'\\nComponent last updated dates:')\n"
            "        for comp, band in list(weight_bands.items())[:10]:\n"
            "            last_updated = band.get('last_updated', 0)\n"
            "            sample_count = band.get('sample_count', 0)\n"
            "            wins = band.get('wins', 0)\n"
            "            losses = band.get('losses', 0)\n"
            "            win_rate = (wins / (wins + losses) * 100) if (wins + losses) > 0 else 0\n"
            "            print(f'  {comp:25} = {sample_count:4} samples, {wins:3}W/{losses:3}L ({win_rate:.1f}%), updated: {last_updated}')\n"
            "\n"
            "print()\n"
            "PYEOF",
            timeout=180
        )
        print(result['stdout'])
        print()
        
    except Exception as e:
        print(f"[ERROR] Analysis failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        client.close()

if __name__ == "__main__":
    main()

