#!/usr/bin/env python3
"""
Alpaca Loss Causality — Phase 2. Reads TRADES_FROZEN (and optional TRADE_TELEMETRY),
computes direction_correct, regime_mismatch, aggregates by cause/regime/symbol/TOD,
appends or writes reports/audit/ALPACA_LOSS_CAUSALITY.md.
READ-ONLY.
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
AUDIT = REPO / "reports" / "audit"


def _float(x, default=0.0):
    try:
        return float(x) if x not in (None, "") else default
    except (TypeError, ValueError):
        return default


def load_frozen(path: Path) -> list[dict]:
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append(dict(r))
    return rows


def run(frozen_csv: Path, telemetry_csv: Path | None, out_md: Path) -> None:
    rows = load_frozen(frozen_csv)
    if not rows:
        return
    # Direction correctness: long correct if exit > entry, short if exit < entry
    for r in rows:
        ep, xp = _float(r.get("entry_price")), _float(r.get("exit_price"))
        side = (r.get("side") or "long").strip().lower()
        if side in ("short", "sell"):
            r["_direction_correct"] = 1 if xp < ep else 0
        else:
            r["_direction_correct"] = 1 if xp > ep else 0
        r["_regime_mismatch"] = 1 if (r.get("entry_regime") or "").strip() != (r.get("exit_regime") or "").strip() else 0
        r["_pnl"] = _float(r.get("realized_pnl_usd"))
        r["_hour"] = (r.get("entry_time") or "")[:13]  # YYYY-MM-DDTHH

    # Aggregates
    by_regime: dict[str, list[float]] = defaultdict(list)
    by_symbol: dict[str, list[float]] = defaultdict(list)
    by_tod: dict[str, list[float]] = defaultdict(list)
    wrong_dir_pnl = 0.0
    wrong_dir_n = 0
    regime_mismatch_pnl = 0.0
    regime_mismatch_n = 0

    for r in rows:
        pnl = r["_pnl"]
        reg = (r.get("entry_regime") or "unknown").strip() or "unknown"
        by_regime[reg].append(pnl)
        sym = (r.get("symbol") or "?").strip() or "?"
        by_symbol[sym].append(pnl)
        tod = r["_hour"] or "unknown"
        by_tod[tod].append(pnl)
        if r["_direction_correct"] == 0:
            wrong_dir_pnl += pnl
            wrong_dir_n += 1
        if r["_regime_mismatch"] == 1 and pnl < 0:
            regime_mismatch_pnl += pnl
            regime_mismatch_n += 1

    # Write summary section to out_md (append or overwrite)
    lines = [
        "# Alpaca Loss Causality — Decomposition (Phase 2, QSA)",
        "",
        "**Generated by run_alpaca_loss_causality.py**",
        "",
        "## 2. Aggregates (Computed)",
        "",
        "### 2.1 Loss by Cause (Summary)",
        "",
        "| Cause | Count | Sum PnL |",
        "|-------|-------|---------|",
        f"| Wrong direction | {wrong_dir_n} | {round(wrong_dir_pnl, 2)} |",
        f"| Regime mismatch (on losers) | {regime_mismatch_n} | {round(regime_mismatch_pnl, 2)} |",
        "",
        "### 2.2 Loss by Regime",
        "",
        "| entry_regime | Trades | Total PnL | Win rate | Mean PnL |",
        "|--------------|--------|-----------|----------|----------|",
    ]
    for reg in sorted(by_regime.keys()):
        pnls = by_regime[reg]
        n = len(pnls)
        total = sum(pnls)
        wins = sum(1 for p in pnls if p > 0)
        wr = round(100.0 * wins / n, 1) if n else 0
        mean = round(total / n, 4) if n else 0
        lines.append(f"| {reg} | {n} | {round(total, 2)} | {wr}% | {mean} |")
    lines.extend([
        "",
        "### 2.3 Loss by Symbol",
        "",
        "| Symbol | Trades | Total PnL | Win rate | Mean PnL |",
        "|--------|--------|-----------|----------|----------|",
    ])
    for sym in sorted(by_symbol.keys()):
        pnls = by_symbol[sym]
        n = len(pnls)
        total = sum(pnls)
        wins = sum(1 for p in pnls if p > 0)
        wr = round(100.0 * wins / n, 1) if n else 0
        mean = round(total / n, 4) if n else 0
        lines.append(f"| {sym} | {n} | {round(total, 2)} | {wr}% | {mean} |")
    lines.extend([
        "",
        "### 2.4 Loss by Time-of-Day (entry hour UTC)",
        "",
        "| Hour bucket | Trades | Total PnL | Win rate |",
        "|--------------|--------|-----------|----------|",
    ])
    for tod in sorted(by_tod.keys())[:24]:  # cap for readability
        pnls = by_tod[tod]
        n = len(pnls)
        total = sum(pnls)
        wins = sum(1 for p in pnls if p > 0)
        wr = round(100.0 * wins / n, 1) if n else 0
        lines.append(f"| {tod} | {n} | {round(total, 2)} | {wr}% |")

    out_md.parent.mkdir(parents=True, exist_ok=True)
    with open(out_md, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_md}")


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description="Alpaca Loss Causality — Phase 2")
    ap.add_argument("--frozen", type=Path, required=True, help="TRADES_FROZEN.csv")
    ap.add_argument("--telemetry", type=Path, default=None, help="TRADE_TELEMETRY.csv (optional)")
    ap.add_argument("--out", type=Path, default=AUDIT / "ALPACA_LOSS_CAUSALITY.md", help="Output MD")
    args = ap.parse_args()
    if not args.frozen.exists():
        print(f"Missing {args.frozen}", file=__import__("sys").stderr)
        return 1
    run(args.frozen, args.telemetry, args.out)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
