#!/usr/bin/env python3
"""
Apply a single path-to-profitability overlay (entry or exit) for paper only.
Writes overlay to config/tuning/paper_overlay.json (exit) and/or state/paper_overlay.env (entry).
Does NOT restart the bot; operator must set env and/or GOVERNED_TUNING_CONFIG and restart.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def main() -> int:
    ap = argparse.ArgumentParser(description="Apply paper overlay from overlay_config.json")
    ap.add_argument("--overlay", type=Path, required=True, help="Path to overlay_config.json")
    ap.add_argument("--no_suppression", action="store_true")
    args = ap.parse_args()

    overlay_path = args.overlay.resolve()
    if not overlay_path.exists():
        print(f"Overlay config not found: {overlay_path}", file=sys.stderr)
        return 1

    cfg = json.loads(overlay_path.read_text(encoding="utf-8"))
    lever = (cfg.get("lever") or "").lower()
    change = cfg.get("change") or {}

    if lever not in ("entry", "exit"):
        print(f"Unknown lever: {lever}", file=sys.stderr)
        return 2

    state_dir = REPO / "state"
    tuning_dir = REPO / "config" / "tuning"
    state_dir.mkdir(parents=True, exist_ok=True)
    tuning_dir.mkdir(parents=True, exist_ok=True)

    run_tag = cfg.get("run_tag", "path_to_profitability")
    overlay_start_date = __import__("datetime").datetime.now(__import__("datetime").timezone.utc).strftime("%Y-%m-%d")

    if lever == "entry":
        # Support absolute min_exec_score (entry strength lever) or delta bump
        if change.get("min_exec_score") is not None:
            new_score = round(float(change["min_exec_score"]), 2)
            delta = new_score - float(os.environ.get("MIN_EXEC_SCORE", "2.5"))
        else:
            delta = float(change.get("delta", 0.2))
            current = float(os.environ.get("MIN_EXEC_SCORE", "2.5"))
            new_score = round(current + delta, 2)
        env_path = state_dir / "paper_overlay.env"
        env_path.write_text(
            f"# Path-to-profitability paper overlay (entry)\n"
            f"# Generated by apply_paper_overlay.py\n"
            f"export MIN_EXEC_SCORE={new_score}\n",
            encoding="utf-8",
        )
        print(f"Wrote {env_path} (MIN_EXEC_SCORE={new_score})")
        audit = {
            "lever": "entry",
            "run_tag": run_tag,
            "overlay_start_date": overlay_start_date,
            "min_exec_score_bump": delta,
            "min_exec_score_new": new_score,
            "paper_only": True,
        }
        (state_dir / "path_to_profitability_overlay.json").write_text(
            json.dumps(audit, indent=2), encoding="utf-8"
        )
        print("To activate: source state/paper_overlay.env and restart paper bot.")

    else:
        strength = float(change.get("strength", 0.05))
        # Base flow_deterioration from common overlay (0.22); add strength
        flow_val = round(0.22 + strength, 2)
        paper_overlay = {
            "version": f"{run_tag}_paper",
            "exit_weights": {"flow_deterioration": flow_val},
        }
        overlay_file = tuning_dir / "paper_overlay.json"
        overlay_file.write_text(json.dumps(paper_overlay, indent=2), encoding="utf-8")
        print(f"Wrote {overlay_file} (flow_deterioration={flow_val})")
        audit = {
            "lever": "exit",
            "run_tag": run_tag,
            "overlay_start_date": overlay_start_date,
            "exit_tweak_strength": strength,
            "flow_deterioration": flow_val,
            "paper_only": True,
        }
        (state_dir / "path_to_profitability_overlay.json").write_text(
            json.dumps(audit, indent=2), encoding="utf-8"
        )
        print("To activate: set GOVERNED_TUNING_CONFIG=config/tuning/paper_overlay.json and restart paper bot.")

    # Write overlay_start_date into overlay config for the wait loop
    cfg["overlay_start_date"] = overlay_start_date
    overlay_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
