/**
 * Weekly Governance Summary — Automation instructions for Cursor Cloud Agent
 * Trigger: Weekly, Sunday 00:00 UTC (cron 0 0 * * 0).
 *
 * Copy or adapt this logic into the automation prompt at cursor.com/automations.
 */

// === INSTRUCTIONS FOR THE AGENT ===
//
// 1. Run on the repository (main branch). Use the current date (or last Sunday) for the report filename.
//    Format: reports/board/WEEKLY_GOVERNANCE_SUMMARY_<YYYY-MM-DD>.md
//
// 2. Gather the following (from git history, branch state, and repo files) for the past 7 days:
//
//    a) COMMITS TO MAIN
//       - Count and list (or summarize) commits to main in the last 7 days. Use git log.
//
//    b) PRs MERGED
//       - If GitHub API or PR context is available: count and list merged PRs (titles, numbers) in the last 7 days. Otherwise note "Manual check: GitHub PR list for repo, merged in last 7 days."
//
//    c) CSA VERDICTS
//       - List reports/audit/CSA_VERDICT_*.json (or CSA_VERDICT_LATEST.json) and their verdict/date if present. Summarize: PROCEED / HOLD / ESCALATE / ROLLBACK and mission_id.
//
//    d) SRE ANOMALIES
//       - If reports/audit/SRE_STATUS.json or similar exists, summarize. Otherwise: "No SRE status file found; check droplet or audit docs."
//
//    e) DEPLOYS
//       - From reports/audit/: any DEPLOYMENT_PROOF, DEPLOY_*, or B2_* proof files updated in the last 7 days. One-line summary per artifact.
//
//    f) SHADOW / PAPER / LIVE CHANGES
//       - Any changes to shadow runs, paper trading flags, or live enablement (e.g. B2_LIVE_PAPER_ENABLE_PROOF, shadow comparison reports). Summarize from reports/audit/ and reports/board/.
//
//    g) CONFIG CHANGES
//       - Notable config or env changes in main in the last 7 days (e.g. .cursor/deployment.json, env examples, feature flags in code). Brief list or "None detected."
//
// 3. Write a single Markdown report to reports/board/WEEKLY_GOVERNANCE_SUMMARY_<YYYY-MM-DD>.md with this structure:
//
//    # Weekly Governance Summary — <YYYY-MM-DD>
//
//    ## Commits to main
//    ...
//
//    ## PRs merged
//    ...
//
//    ## CSA verdicts
//    ...
//
//    ## SRE anomalies
//    ...
//
//    ## Deploys
//    ...
//
//    ## Shadow / paper / live changes
//    ...
//
//    ## Config changes
//    ...
//
//    ---
//    *Generated by Cursor Automation (weekly_governance_summary).*
//
// 4. If SLACK_WEBHOOK_URL is set in environment, post a short summary to the configured Slack channel: title "Weekly Governance Summary — <date>", and 1–2 lines per section (or a link to the report if the repo is visible).
//
// 5. Do not modify droplet code or runtime. Only read repo/git and write the report file. If the automation can commit, commit and push only this new/updated report file; otherwise write to workspace and note in run summary.

export const REPORT_FILENAME_PREFIX = 'WEEKLY_GOVERNANCE_SUMMARY_';
