#!/usr/bin/env python3
"""
Generate daily SIGNAL_MAP report from logs/signal_snapshots.jsonl.
Observability-only. No account/order IDs.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SNAPSHOTS_LOG = Path("logs/signal_snapshots.jsonl")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=None)
    ap.add_argument("--symbols", default="AAPL", help="Comma-separated (default: AAPL + top traded)")
    ap.add_argument("--base-dir", default=None)
    ap.add_argument("--snapshots-path", default=None, help="Override path (e.g. logs/signal_snapshots_harness_YYYY-MM-DD.jsonl)")
    args = ap.parse_args()

    base = Path(args.base_dir) if args.base_dir else REPO
    target_date = args.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    symbols_arg = [s.strip() for s in (args.symbols or "AAPL").split(",") if s.strip()]

    snapshots_path = args.snapshots_path or str(SNAPSHOTS_LOG)
    log_path = base / snapshots_path
    source_label = "HARNESS" if "harness" in snapshots_path else "REALTIME"
    if not log_path.exists():
        reports_dir = base / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        out_path = reports_dir / f"SIGNAL_MAP_{target_date}.md"
        out_path.write_text(
            f"# Signal Map — {target_date}\n\n"
            "**No snapshots found.** Ensure `logs/signal_snapshots.jsonl` exists and contains records.\n\n"
            "*Generated by scripts/generate_daily_signal_map_report.py*\n",
            encoding="utf-8",
        )
        print(f"Wrote empty report: {out_path}")
        return 0

    records = []
    with log_path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            ts = rec.get("timestamp_utc") or ""
            if target_date and not ts.startswith(target_date):
                continue
            records.append(rec)

    symbols = set(symbols_arg)
    if "AAPL" not in symbols:
        symbols.add("AAPL")
    for r in records:
        s = r.get("symbol")
        if s:
            symbols.add(str(s).upper())

    lines = [
        f"# Signal Map — {target_date}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        f"**Source:** {source_label}",
        "",
        "## Summary",
        "",
        f"- Total snapshots (date-filtered): {len(records)}",
        f"- Symbols: {', '.join(sorted(symbols)[:30])}{'...' if len(symbols) > 30 else ''}",
        "",
        "---",
        "",
    ]

    for sym in sorted(symbols):
        sym_records = [r for r in records if str(r.get("symbol", "")).upper() == sym]
        if not sym_records:
            continue
        lines.append(f"## {sym}")
        lines.append("")
        for r in sym_records:
            ev = r.get("lifecycle_event", "")
            mode = r.get("mode", "")
            score = r.get("composite_score_v2")
            fresh = r.get("freshness_factor")
            comps = r.get("components") or {}
            present = [k for k, v in comps.items() if isinstance(v, dict) and v.get("present")]
            defaulted = [k for k, v in comps.items() if isinstance(v, dict) and v.get("defaulted")]
            missing = [k for k, v in comps.items() if isinstance(v, dict) and not v.get("present") and not v.get("defaulted")]
            notes = r.get("notes") or []
            lines.append(f"- **{ev}** ({mode}) | score={score} | freshness={fresh}")
            lines.append(f"  - Present: {', '.join(present[:10])}{'...' if len(present) > 10 else ''}")
            lines.append(f"  - Defaulted: {', '.join(defaulted[:10])}{'...' if len(defaulted) > 10 else ''}")
            if missing:
                lines.append(f"  - Missing: {', '.join(missing[:10])}{'...' if len(missing) > 10 else ''}")
            if notes:
                lines.append(f"  - Notes: {'; '.join(notes[:5])}")
            lines.append("")
        lines.append("")

    reports_dir = base / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    out_path = reports_dir / f"SIGNAL_MAP_{target_date}.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
