#!/usr/bin/env python3
"""
Exit Join Health Report. NO-APPLY.
Snapshot→exit match rate, unmatched reasons, before/after comparison.
Output: reports/EXIT_JOIN_HEALTH_<DATE>.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


def _load_jsonl(path: Path) -> list:
    out = []
    if not path.exists():
        return out
    with path.open("r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", required=True)
    ap.add_argument("--base-dir", default=None)
    ap.add_argument("--snapshots-path", default="logs/signal_snapshots.jsonl")
    args = ap.parse_args()

    base = Path(args.base_dir) if args.base_dir else REPO
    target_date = args.date
    logs_dir = base / "logs"
    state_dir = base / "state"
    reports_dir = base / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    snap_path = base / args.snapshots_path
    snapshots = _load_jsonl(snap_path)
    master_log = _load_jsonl(logs_dir / "master_trade_log.jsonl")
    exit_attr = _load_jsonl(logs_dir / "exit_attribution.jsonl")

    def in_date(ts: str) -> bool:
        return str(ts or "")[:10] == target_date if ts else False

    snapshots = [s for s in snapshots if in_date(s.get("timestamp_utc", ""))]
    master_log = [m for m in master_log if in_date(m.get("entry_ts") or m.get("timestamp", ""))]
    exit_attr = [e for e in exit_attr if in_date(e.get("timestamp") or e.get("entry_timestamp", ""))]

    exit_snapshots = [s for s in snapshots if s.get("lifecycle_event") in ("EXIT_DECISION", "EXIT_FILL")]

    from telemetry.exit_join_reconciler import reconcile_exit_snapshots_to_outcomes

    stats = reconcile_exit_snapshots_to_outcomes(exit_snapshots, master_log, exit_attr)

    total = stats["total_exit_snapshots"]
    matched_tid = stats["matched_by_trade_id"]
    matched_sur = stats["matched_by_surrogate"]
    unmatched = stats["unmatched"]
    match_rate = (matched_tid + matched_sur) / total * 100.0 if total else 0.0

    lines = [
        f"# Exit Join Health — {target_date}",
        "",
        "**Generated:** Observability-only. NO-APPLY.",
        "",
        "## 1. Snapshot→Exit Match Rate",
        "",
        f"- Exit snapshots (EXIT_DECISION + EXIT_FILL): {total}",
        f"- Matched by trade_id: {matched_tid}",
        f"- Matched by surrogate/time-window: {matched_sur}",
        f"- Unmatched: {unmatched}",
        f"- **Match rate: {match_rate:.1f}%**",
        "",
        "## 2. Unmatched Reasons",
        "",
    ]
    for k, v in sorted(stats.get("reasons", {}).items(), key=lambda x: -x[1]):
        lines.append(f"- {k}: {v}")
    if not stats.get("reasons"):
        lines.append("- (none)")
    lines.extend([
        "",
        "## 3. Exit Sources",
        "",
        f"- Master trade log (exited): {stats['total_exits_mtl']}",
        f"- Exit attribution: {stats['total_exits_ea']}",
        "",
        "---",
        "*Generated by scripts/generate_exit_join_health_report.py*",
    ])

    out_path = reports_dir / f"EXIT_JOIN_HEALTH_{target_date}.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
