#!/usr/bin/env python3
"""
CSA wrapper: run full CSA profitability review every 100 trade events.
Called by primary trigger (trading engine) and backup trigger (droplet post-trade hook).
Creates CSA_VERDICT_<mission_id>.json, CSA_FINDINGS_<mission_id>.md, and board report CSA_TRADE_100_<date>.md.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
AUDIT_DIR = REPO / "reports" / "audit"
BOARD_DIR = REPO / "reports" / "board"


def main() -> int:
    ap = argparse.ArgumentParser(description="Run CSA every-100-trades review")
    ap.add_argument("--mission-id", required=True, help="e.g. CSA_TRADE_100_20260306-001234")
    ap.add_argument("--trade-count", type=int, default=0, help="Trade count at trigger (for report)")
    args = ap.parse_args()

    mission_id = args.mission_id
    board_review = REPO / "reports" / "board" / "last387_comprehensive_review.json"
    shadow_comparison = REPO / "reports" / "board" / "SHADOW_COMPARISON_LAST387.json"
    sre_status = REPO / "reports" / "audit" / "SRE_STATUS.json"

    cmd = [
        sys.executable,
        str(REPO / "scripts" / "audit" / "run_chief_strategy_auditor.py"),
        "--mission-id", mission_id,
        "--base-dir", str(REPO),
    ]
    if board_review.exists():
        cmd.extend(["--board-review-json", str(board_review)])
    if shadow_comparison.exists():
        cmd.extend(["--shadow-comparison-json", str(shadow_comparison)])
    if sre_status.exists():
        cmd.extend(["--sre-status-json", str(sre_status)])

    rc = subprocess.call(cmd, cwd=str(REPO))
    if rc != 0:
        return rc

    # Board-grade summary for this 100-trade run
    verdict_path = AUDIT_DIR / f"CSA_VERDICT_{mission_id}.json"
    findings_path = AUDIT_DIR / f"CSA_FINDINGS_{mission_id}.md"
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    board_report = BOARD_DIR / f"CSA_TRADE_100_{date_str}.md"

    BOARD_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# CSA Trade 100 Review — " + date_str,
        "",
        f"**Mission ID:** {mission_id}",
        f"**Trade count at trigger:** {args.trade_count}",
        f"**Generated (UTC):** {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Artifacts",
        "",
        f"- Verdict: `reports/audit/CSA_VERDICT_{mission_id}.json`",
        f"- Findings: `reports/audit/CSA_FINDINGS_{mission_id}.md`",
        f"- Latest: `reports/audit/CSA_VERDICT_LATEST.json`, `reports/audit/CSA_SUMMARY_LATEST.md`",
        "",
    ]
    if verdict_path.exists():
        try:
            v = json.loads(verdict_path.read_text(encoding="utf-8"))
            lines.extend([
                "## Verdict summary",
                "",
                f"- **Verdict:** {v.get('verdict', 'N/A')}",
                f"- **Confidence:** {v.get('confidence', 'N/A')}",
                f"- **Recommendation:** {v.get('recommendation', 'N/A')}",
                "",
            ])
        except Exception:
            pass
    lines.append("---\n*Generated by scripts/run_csa_every_100_trades.py.*")
    board_report.write_text("\n".join(lines), encoding="utf-8")

    # Refresh Profitability & Learning dashboard so cockpit shows this CSA run
    cockpit_script = REPO / "scripts" / "update_profitability_cockpit.py"
    if cockpit_script.exists():
        subprocess.call([sys.executable, str(cockpit_script)], cwd=str(REPO))

    return 0


if __name__ == "__main__":
    sys.exit(main())
