#!/usr/bin/env python3
"""
Molt workflow synthesis (stub only).
Loads Molt artifacts and writes reports/MOLT_OPENCLAW_SYNTHESIS_<date>.md with a stub.
No external agent; Clawdbot integration was removed.
NO-APPLY: all outputs are advisory for human review.
"""
from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)


def run_openclaw_synthesis(date: str, base_dir: Path, dry_run: bool = False) -> int:
    """
    Load Molt artifacts and write reports/MOLT_OPENCLAW_SYNTHESIS_<date>.md (stub only).
    No external agent; Clawdbot integration was removed. Never raises; returns 0.
    """
    _ = dry_run  # kept for backward compatibility
    reports_dir = base_dir / "reports"
    out_path = reports_dir / f"MOLT_OPENCLAW_SYNTHESIS_{date}.md"

    stub = {
        "operator_actions": ["[Stub] Clawdbot/OpenClaw integration removed. Review Molt artifacts manually."],
        "memory_bank_suggestion": None,
    }
    _write_synthesis_md(out_path, date, stub)
    log.info("Wrote stub synthesis to %s (no external agent)", out_path)
    return 0


def _write_synthesis_md(path: Path, date: str, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Molt → OpenClaw Synthesis — {date}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "**NO-APPLY.** Advisory only. Human review required.",
        "",
        "## Operator Actions",
        "",
    ]
    for item in data.get("operator_actions") or []:
        lines.append(f"- {item}")
    lines.extend([
        "",
        "## Memory Bank Suggestion (NOT APPLIED)",
        "",
    ])
    suggestion = data.get("memory_bank_suggestion")
    if suggestion:
        lines.append(suggestion)
        lines.append("")
        lines.append("*This is a suggestion only. Do not apply unless explicitly approved.*")
    else:
        lines.append("*None.*")
    lines.extend([
        "",
        "---",
        "*Generated by scripts/run_openclaw_molt_synthesis.py. NO-APPLY.*",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Molt workflow → OpenClaw synthesis (NO-APPLY)")
    ap.add_argument("--date", default=None, help="YYYY-MM-DD (default: today UTC)")
    ap.add_argument("--base-dir", default=None, help="Repo root (default: script parent)")
    ap.add_argument("--dry-run", action="store_true", help="Skip OpenClaw call, write stub")
    args = ap.parse_args()
    base = Path(args.base_dir) if args.base_dir else REPO
    date = args.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return run_openclaw_synthesis(date, base, dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
