"""
Molt Multi-Agent Learning Board.
Runs signal_advocate, risk_auditor, counterfactual_analyst, governance_chair.
Synthesizes PROMOTION_PROPOSAL_<DATE>.md or REJECTION_WITH_REASON_<DATE>.md
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .agents import (
    run_signal_advocate,
    run_risk_auditor,
    run_counterfactual_analyst,
    run_governance_chair,
)


def run_learning_board(
    date: str,
    base_dir: Optional[Path] = None,
) -> str:
    """
    Run multi-agent learning board.
    Returns: "PROPOSE" or "REJECT"
    """
    base = base_dir or Path(__file__).resolve().parents[1]
    reports_dir = base / "reports"

    v1 = run_signal_advocate(date, base)
    v2 = run_risk_auditor(date, base)
    v3 = run_counterfactual_analyst(date, base)
    chair = run_governance_chair([v1, v2, v3], date)

    if chair["verdict"] == "PROPOSE":
        out_path = reports_dir / f"PROMOTION_PROPOSAL_{date}.md"
        lines = [
            f"# Promotion Proposal — {date}",
            "",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            "**NO-APPLY.** Proposal only. Human approval required.",
            "",
            "## Governance Chair Verdict",
            "",
            f"- **Verdict:** {chair['verdict']}",
            f"- **Reason:** {chair['reason']}",
            "",
            "## Agent Verdicts",
            "",
            "| Agent | Verdict | Reason |",
            "|-------|---------|--------|",
        ]
        for d in chair.get("details", []):
            lines.append(f"| {d.get('agent', '')} | {d.get('verdict', '')} | {d.get('reason', '')[:60]} |")
        lines.extend([
            "",
            "---",
            "*Generated by moltbot/board.py. NO-APPLY.*",
        ])
    else:
        out_path = reports_dir / f"REJECTION_WITH_REASON_{date}.md"
        lines = [
            f"# Rejection With Reason — {date}",
            "",
            f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
            "**NO-APPLY.**",
            "",
            "## Governance Chair Verdict",
            "",
            f"- **Verdict:** {chair['verdict']}",
            f"- **Reason:** {chair['reason']}",
            "",
            "## Agent Verdicts",
            "",
            "| Agent | Verdict | Reason |",
            "|-------|---------|--------|",
        ]
        for d in chair.get("details", []):
            lines.append(f"| {d.get('agent', '')} | {d.get('verdict', '')} | {d.get('reason', '')[:60]} |")
        lines.extend([
            "",
            "---",
            "*Generated by moltbot/board.py. NO-APPLY.*",
        ])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return chair["verdict"]
