"""
Molt Memory Bank Evolution Proposer.
Detects repeated learning patterns, proposes Memory Bank updates.
Output: reports/MEMORY_BANK_CHANGE_PROPOSAL_<DATE>.md
Never writes Memory Bank directly.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parents[1]


def _scan_recent_reports(base: Path, date: str, days: int = 7) -> List[str]:
    """Scan recent LEARNING_STATUS, ENGINEERING_HEALTH for patterns."""
    from datetime import datetime as dt, timedelta
    patterns = []
    try:
        d = dt.strptime(date, "%Y-%m-%d")
    except Exception:
        return patterns
    for i in range(days):
        check_date = (d - timedelta(days=i)).strftime("%Y-%m-%d")
        for name in ["LEARNING_STATUS", "ENGINEERING_HEALTH", "PROMOTION_PROPOSAL", "REJECTION_WITH_REASON"]:
            p = base / "reports" / f"{name}_{check_date}.md"
            if p.exists():
                text = p.read_text(encoding="utf-8", errors="replace")
                if "LEARNING_FAILED" in text:
                    patterns.append(f"LEARNING_FAILED repeated ({check_date})")
                if "DEGRADED" in text:
                    patterns.append(f"ENGINEERING_DEGRADED ({check_date})")
    return list(set(patterns))


def run_memory_evolution_proposal(
    date: str,
    base_dir: Optional[Path] = None,
) -> None:
    """
    Generate Memory Bank change proposal. Never writes MEMORY_BANK.md.
    """
    base = base_dir or REPO
    reports_dir = base / "reports"
    patterns = _scan_recent_reports(base, date)
    proposals: List[str] = []
    if any("LEARNING_FAILED" in p for p in patterns):
        proposals.append("- Consider adding LEARNING_STATUS to EOD bundle validation in §5.5")
    if any("DEGRADED" in p for p in patterns):
        proposals.append("- Consider adding ENGINEERING_HEALTH to post-market cron in §6")
    if not proposals:
        proposals.append("- No recurring failure patterns detected; no changes proposed")

    lines = [
        f"# Memory Bank Change Proposal — {date}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "**NO-APPLY.** Molt proposes; human approves. Never writes MEMORY_BANK directly.",
        "",
        "## Detected Patterns",
        "",
    ]
    if patterns:
        for p in patterns[:10]:
            lines.append(f"- {p}")
    else:
        lines.append("- (No patterns in recent reports)")
    lines.extend([
        "",
        "## Proposed Changes",
        "",
    ])
    for prop in proposals:
        lines.append(prop)
    lines.extend([
        "",
        "## Approval Required",
        "",
        "Molt does NOT modify MEMORY_BANK.md. Cursor/human must apply approved changes.",
        "",
        "---",
        "*Generated by moltbot/memory_evolution.py*",
    ])
    out_path = reports_dir / f"MEMORY_BANK_CHANGE_PROPOSAL_{date}.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
