"""
Molt Learning Orchestrator — stock_bot_learning_orchestrator.
Verifies Memory Bank version, learning pipeline artifacts, NO-APPLY compliance.
Output: reports/LEARNING_STATUS_<DATE>.md
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parents[1]
MEMORY_BANK = REPO / "MEMORY_BANK.md"

REQUIRED_SECTIONS = [
    "GOLDEN WORKFLOW",
    "Signal Snapshot Mapping Layer",
    "Snapshot→Outcome Attribution",
    "Exit Join Canonicalization",
    "Blocked-Trade Intelligence Attribution",
    "Shadow snapshot profiles",
    "UW canonical rules",
]

LEARNING_ARTIFACTS = [
    ("reports/SNAPSHOT_OUTCOME_ATTRIBUTION_{date}.md", "Snapshot outcome attribution"),
    ("reports/EXIT_JOIN_HEALTH_{date}.md", "Exit join health"),
    ("reports/BLOCKED_TRADE_INTEL_{date}.md", "Blocked trade intel"),
    ("reports/SIGNAL_MAP_{date}.md", "Signal map"),
    ("config/shadow_snapshot_profiles.yaml", "Shadow profiles config"),
]


def _read_memory_bank() -> str:
    if not MEMORY_BANK.exists():
        return ""
    return MEMORY_BANK.read_text(encoding="utf-8", errors="replace")


def _check_no_apply_compliance() -> List[str]:
    """Verify NO-APPLY markers in key configs and reports."""
    issues = []
    shadow_profiles = REPO / "config" / "shadow_snapshot_profiles.yaml"
    if shadow_profiles.exists():
        text = shadow_profiles.read_text(encoding="utf-8", errors="replace")
        if "NO-APPLY" not in text.upper() and "no apply" not in text.lower():
            issues.append("config/shadow_snapshot_profiles.yaml missing NO-APPLY disclaimer")
    return issues


def run_learning_orchestrator(
    date: str,
    universe: Optional[List[str]] = None,
    base_dir: Optional[Path] = None,
) -> str:
    """
    Run stock_bot_learning_orchestrator.
    Returns: LEARNING_COMPLETE or LEARNING_FAILED
    """
    base = base_dir or REPO
    mb_text = _read_memory_bank()

    checks: Dict[str, Any] = {
        "memory_bank_version": None,
        "required_sections": [],
        "learning_artifacts": [],
        "no_apply_compliance": [],
        "verdict": "LEARNING_FAILED",
    }

    for sec in REQUIRED_SECTIONS:
        present = sec.upper() in mb_text.upper() or sec in mb_text
        checks["required_sections"].append({"section": sec, "present": present})

    for path_tpl, desc in LEARNING_ARTIFACTS:
        path = base / path_tpl.format(date=date)
        if "{date}" not in path_tpl:
            path = base / path_tpl
        exists = path.exists() and path.stat().st_size > 0
        checks["learning_artifacts"].append({"path": str(path.relative_to(base)), "exists": exists, "description": desc})

    no_apply_issues = _check_no_apply_compliance()
    checks["no_apply_compliance"] = no_apply_issues

    all_sections_ok = all(s["present"] for s in checks["required_sections"])
    no_apply_ok = len(no_apply_issues) == 0

    if all_sections_ok and no_apply_ok:
        checks["verdict"] = "LEARNING_COMPLETE"
    else:
        checks["verdict"] = "LEARNING_FAILED"

    out_path = base / "reports" / f"LEARNING_STATUS_{date}.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Learning Status — {date}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "**NO-APPLY.** Molt produces artifacts only.",
        "",
        "## Verdict",
        "",
        f"**{checks['verdict']}**",
        "",
        "## Memory Bank",
        "",
        f"- Version check: {mb_text[:200] if mb_text else 'MISSING'}...",
        "- Required sections:",
    ]
    for s in checks["required_sections"]:
        status = "PASS" if s["present"] else "FAIL"
        lines.append(f"  - {s['section']}: {status}")
    lines.extend([
        "",
        "## Learning Artifacts",
        "",
    ])
    for a in checks["learning_artifacts"]:
        status = "present" if a["exists"] else "missing"
        lines.append(f"- {a['description']} ({a['path']}): {status}")
    lines.extend([
        "",
        "## NO-APPLY Compliance",
        "",
    ])
    if no_apply_issues:
        for i in no_apply_issues:
            lines.append(f"- FAIL: {i}")
    else:
        lines.append("- PASS: Shadow profiles and reports marked NO-APPLY.")
    lines.extend([
        "",
        "---",
        "*Generated by moltbot/orchestrator.py*",
    ])
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return checks["verdict"]
