"""
Molt Engineering Sentinel — scanning role.
Reads cron logs, EXIT_JOIN_HEALTH, BLOCKED_TRADE_INTEL, SNAPSHOT_OUTCOME_ATTRIBUTION.
Output: reports/ENGINEERING_HEALTH_<DATE>.md
No code changes allowed.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parents[1]


def _load_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def _extract_summary(name: str, text: str) -> Dict[str, Any]:
    """Extract key metrics from report text."""
    out: Dict[str, Any] = {"present": bool(text.strip()), "summary": ""}
    if not text:
        return out
    lines = text.split("\n")[:50]
    for line in lines:
        if "match rate" in line.lower() or "verdict" in line.lower() or "total" in line.lower():
            out["summary"] += line.strip() + "; "
    out["summary"] = out["summary"].strip().rstrip(";") or "(no key metrics extracted)"
    return out


def run_engineering_sentinel(
    date: str,
    base_dir: Optional[Path] = None,
) -> None:
    """
    Run engineering_sentinel. Produces ENGINEERING_HEALTH_<DATE>.md.
    No code changes.
    """
    base = base_dir or REPO
    reports_dir = base / "reports"
    logs_dir = base / "logs"

    artifacts = {
        "EXIT_JOIN_HEALTH": _load_text(reports_dir / f"EXIT_JOIN_HEALTH_{date}.md"),
        "BLOCKED_TRADE_INTEL": _load_text(reports_dir / f"BLOCKED_TRADE_INTEL_{date}.md"),
        "SNAPSHOT_OUTCOME_ATTRIBUTION": _load_text(reports_dir / f"SNAPSHOT_OUTCOME_ATTRIBUTION_{date}.md"),
        "LEARNING_STATUS": _load_text(reports_dir / f"LEARNING_STATUS_{date}.md"),
    }

    cron_log = ""
    for p in [logs_dir / "cron_sync.log", base / "cron_sync.log"]:
        if p.exists():
            cron_log = _load_text(p)
            break

    summaries = {k: _extract_summary(k, v) for k, v in artifacts.items()}

    lines = [
        f"# Engineering Health — {date}",
        "",
        f"**Generated:** {datetime.now(timezone.utc).isoformat()}",
        "**NO-APPLY.** Molt scanning role. No code changes.",
        "",
        "## Artifact Presence",
        "",
        "| Artifact | Present | Summary |",
        "|----------|---------|---------|",
    ]
    for name, data in summaries.items():
        pres = "Yes" if data["present"] else "No"
        summ = (data["summary"] or "-")[:80]
        lines.append(f"| {name} | {pres} | {summ} |")

    lines.extend([
        "",
        "## Cron Sync",
        "",
        f"Cron log present: {bool(cron_log.strip())}",
        "",
        "## Verdict",
        "",
    ])
    all_present = all(a["present"] for a in summaries.values())
    if all_present:
        lines.append("**HEALTHY** — All monitored artifacts present.")
    else:
        missing = [k for k, v in summaries.items() if not v["present"]]
        lines.append(f"**DEGRADED** — Missing: {', '.join(missing)}")

    lines.extend([
        "",
        "---",
        "*Generated by moltbot/sentinel.py*",
    ])
    out_path = reports_dir / f"ENGINEERING_HEALTH_{date}.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
